<a href="https://colab.research.google.com/github/ahmetnihat/ses_analizi/blob/main/Deep_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install --upgrade tensorflow
!pip install --upgrade keras

In [ ]:
import librosa
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import os
from PIL import Image
import pathlib
from keras import layers
from keras import layers
import keras


In [ ]:
!pip install joblib

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
import seaborn as sbn
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation, Dropout
from tensorflow.keras.callbacks import EarlyStopping
from sklearn import datasets, svm, metrics 
from sklearn.naive_bayes import GaussianNB
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import classification_report, confusion_matrix 
from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import f1_score,recall_score
from sklearn.model_selection import cross_val_score
from mlxtend.feature_selection import SequentialFeatureSelector as SFS
import sklearn.feature_selection
import numpy as np
import matplotlib.pyplot as plt
from itertools import cycle
from sklearn.neighbors import KNeighborsClassifier
from sklearn import svm, datasets
from sklearn.metrics import roc_curve, auc
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import label_binarize
from sklearn.multiclass import OneVsRestClassifier
from scipy import interp
from sklearn.metrics import roc_auc_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import ConfusionMatrixDisplay
import joblib



In [ ]:
dataFrame

Unnamed: 0  Unnamed: 0.1          0  ...           126           127   Duygu
156            0             0   3.412547  ...  2.848702e-07  2.806970e-07    cats
157            1             0   8.466628  ...  1.478017e-09  1.451570e-09    cats
158            2             0  10.832393  ...  9.613674e-08  9.468492e-08    cats
159            3             0   0.047353  ...  9.388628e-09  9.200760e-09    cats
160            4             0  35.021137  ...  2.541540e-06  2.512498e-06    cats
...          ...           ...        ...  ...           ...           ...     ...
1147         116             0   0.048960  ...  6.894791e-04  1.188264e-04  ciglik
1148         117             0   0.057377  ...  8.691325e-05  4.966762e-06  ciglik
1149         118             0   0.014789  ...  3.489289e-04  1.527595e-05  ciglik
1150         119             0   0.072620  ...  2.250256e-03  4.333480e-05  ciglik
1151         120             0   0.103172  ...  5.264332e-04  8.284847e-05  ciglik

[996 rows x 131 columns]

In [ ]:
dataFrame = pd.read_csv('/content/drive/MyDrive/csvler/melspectr/7li.csv')

selRows = dataFrame[dataFrame['Duygu'] == 'human2'].index
dataFrame = dataFrame.drop(selRows, axis=0)

dataFrame = dataFrame.drop("Unnamed: 0", axis=1)
dataFrame = dataFrame.drop("Unnamed: 0.1", axis=1)
dataFrame= dataFrame.replace(to_replace ="oksurme",value =3)
dataFrame= dataFrame.replace(to_replace ="ciglik",value =4)
dataFrame= dataFrame.replace(to_replace ="nefes",value =5)

dataFrame= dataFrame.replace(to_replace ="human",value =0)
dataFrame= dataFrame.replace(to_replace ="dogs",value =1)
dataFrame= dataFrame.replace(to_replace ="cats",value =2)

In [ ]:
dataFrame = pd.read_csv('/content/drive/MyDrive/csvler/melspectr/7li.csv')
dataFrame = dataFrame.drop("Unnamed: 0", axis=1)
dataFrame = dataFrame.drop("Unnamed: 0.1", axis=1)
dataFrame= dataFrame.replace(to_replace ="human2",value =1)
dataFrame= dataFrame.replace(to_replace ="human",value =1)
dataFrame= dataFrame.replace(to_replace ="oksurme",value =1)
dataFrame= dataFrame.replace(to_replace ="nefes",value =1)
dataFrame= dataFrame.replace(to_replace ="ciglik",value =1)
dataFrame= dataFrame.replace(to_replace ="dogs",value =2)
dataFrame= dataFrame.replace(to_replace ="cats",value =2)

In [ ]:
dataFrame = pd.read_csv('/content/drive/MyDrive/csvler/librosasonmfcc40/7li.csv')
selRows = dataFrame[dataFrame['Duygu'] == 'human2'].index
dataFrame = dataFrame.drop(selRows, axis=0)

dataFrame = dataFrame.drop("Unnamed: 0", axis=1)
dataFrame = dataFrame.drop("Unnamed: 0.1", axis=1)
dataFrame= dataFrame.replace(to_replace ="oksurme",value =3)
dataFrame= dataFrame.replace(to_replace ="ciglik",value =4)
dataFrame= dataFrame.replace(to_replace ="nefes",value =5)

dataFrame= dataFrame.replace(to_replace ="human",value =0)
dataFrame= dataFrame.replace(to_replace ="dogs",value =1)
dataFrame= dataFrame.replace(to_replace ="cats",value =2)

In [ ]:
y = dataFrame["Duygu"].values
X = dataFrame.drop("Duygu",axis = 1).values
x_train, x_test, y_train, y_test = train_test_split(X,y,test_size=0.3, random_state=15)
scaler = MinMaxScaler()
scaler.fit(x_train)
x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)

In [ ]:
model = Sequential()
model.add(layers.Dense(256, activation='relu', input_shape=(x_train.shape[1],)))
model.add(layers.Dense(128, activation='relu'))
model.add(layers.Dense(64, activation='relu'))
model.add(layers.Dense(10, activation='softmax'))
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [ ]:
model.fit(x_train,y_train,epochs=50,batch_size=128)
action = model.predict(x_test)


Epoch 1/50
6/6 [==============================] - 0s 4ms/step - loss: 2.2734 - accuracy: 0.2100
Epoch 2/50
6/6 [==============================] - 0s 4ms/step - loss: 2.0637 - accuracy: 0.2583
Epoch 3/50
6/6 [==============================] - 0s 4ms/step - loss: 1.8993 - accuracy: 0.2583
Epoch 4/50
6/6 [==============================] - 0s 3ms/step - loss: 1.7508 - accuracy: 0.2810
Epoch 5/50
6/6 [==============================] - 0s 3ms/step - loss: 1.6270 - accuracy: 0.3973
Epoch 6/50
6/6 [==============================] - 0s 5ms/step - loss: 1.5298 - accuracy: 0.4305
Epoch 7/50
6/6 [==============================] - 0s 4ms/step - loss: 1.4397 - accuracy: 0.4970
Epoch 8/50
6/6 [==============================] - 0s 4ms/step - loss: 1.3317 - accuracy: 0.5045
Epoch 9/50
6/6 [==============================] - 0s 4ms/step - loss: 1.2263 - accuracy: 0.6284
Epoch 10/50
6/6 [==============================] - 0s 5ms/step - loss: 1.1401 - accuracy: 0.6314
Epoch 11/50
6/6 [======================

In [ ]:
model.summary()

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_16 (Dense)             (None, 256)               10496     
_________________________________________________________________
dense_17 (Dense)             (None, 128)               32896     
_________________________________________________________________
dense_18 (Dense)             (None, 64)                8256      
_________________________________________________________________
dense_19 (Dense)             (None, 10)                650       
Total params: 52,298
Trainable params: 52,298
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.save('modelkeras')
model = keras.models.load_model('modelkeras')


In [ ]:
from keras.models import Sequential
from keras.layers import Dense
from sklearn.datasets import make_blobs
from sklearn.preprocessing import MinMaxScaler

In [ ]:
y_pred = model.predict(x_test)
y_pred = np.round(y_pred).astype(int)
y_ttest =  np.round(y_test).astype(int)

In [ ]:
y_test

array([0, 3, 0, 0, 0, 0, 5, 4, 2, 3, 2, 2, 0, 1, 0, 5, 1, 1, 4, 4, 2, 2,
       3, 3, 0, 2, 2, 4, 1, 5, 3, 3, 0, 2, 0, 0, 2, 0, 0, 0, 3, 5, 5, 0,
       2, 4, 0, 3, 3, 0, 1, 0, 0, 4, 2, 0, 5, 4, 2, 0, 2, 0, 4, 2, 0, 3,
       4, 3, 4, 3, 2, 2, 2, 3, 2, 5, 0, 3, 0, 3, 5, 5, 2, 1, 1, 2, 4, 1,
       0, 0, 0, 1, 0, 1, 2, 0, 2, 3, 1, 5, 0, 3, 0, 0, 0, 5, 2, 2, 0, 4,
       2, 3, 2, 3, 5, 1, 5, 5, 0, 0, 0, 4, 4, 3, 4, 5, 4, 3, 5, 0, 3, 4,
       0, 3, 3, 5, 3, 4, 5, 5, 1, 2, 0, 3, 2, 0, 0, 3, 3, 2, 1, 3, 0, 0,
       3, 0, 1, 1, 3, 2, 1, 4, 0, 2, 3, 5, 0, 1, 2, 3, 2, 3, 3, 4, 5, 0,
       1, 0, 4, 0, 1, 0, 0, 4, 3, 3, 4, 3, 0, 0, 0, 0, 3, 4, 0, 4, 1, 5,
       3, 5, 0, 3, 3, 3, 1, 5, 5, 3, 4, 4, 2, 1, 1, 3, 0, 4, 4, 1, 2, 2,
       0, 0, 4, 5, 2, 4, 5, 0, 2, 2, 2, 3, 4, 0, 5, 2, 2, 3, 3, 3, 0, 0,
       0, 0, 0, 1, 2, 5, 1, 0, 3, 5, 1, 2, 2, 0, 3, 1, 3, 3, 0, 4, 0, 4,
       2, 4, 1, 0, 0, 5, 3, 0, 3, 4, 4, 0, 0, 5, 0, 3, 4, 3, 2, 1, 4])

In [ ]:
for i in range(0,346):
  print(y_pred[i])


In [ ]:
y_test.shape

(346,)

In [ ]:
predicted_categories = np.argmax(y_pred, axis = 1)
predicted_categories[:2]

array([0, 3])

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.6.0


In [ ]:

# multilayer perceptron model for the two circles problem
from sklearn.datasets import make_circles
from keras.models import Sequential
from keras.layers import Dense
from matplotlib import pyplot

# evaluate the model
_, train_acc = model.evaluate(x_train, y_train, verbose=0)
_, test_acc = model.evaluate(x_test, y_test, verbose=0)
print('Train: %.3f, Test: %.3f' % (train_acc, test_acc))
# plot loss during training


Train: 0.849, Test: 0.832


In [ ]:
import joblib
import librosa
import os
say = 0
insann = 0
dosyas = os.scandir('/content/drive/MyDrive/sesler/')
for i in dosyas:
  dosya_isim = i.name
  say = say + 1
  
  x,sr = librosa.load('/content/drive/MyDrive/sesler/'  + dosya_isim )

  mfccs=librosa.feature.melspectrogram(y=x, sr=sr)
  mfccs_processed = np.mean(mfccs.T,axis=0)
  result = np.array(mfccs_processed)
  mfkkk = pd.DataFrame(result)
  scaler = MinMaxScaler()
  scaler.fit(mfkkk)
  mfkkk = scaler.transform(mfkkk) 
  mfkkk = mfkkk.transpose()


  print(dosya_isim)
  tahmin = model.predict(mfkkk)
  print("tahmin" , tahmin)
  y_pred = np.round(tahmin).astype(int)
  print(y_pred)
  # if tahmin == [3]:
  #   insann = insann + 1
  # print(insann)


/usr/local/lib/python3.7/dist-packages/librosa/core/audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn("PySoundFile failed. Trying audioread instead.")


mutluerdem.m4a
tahmin [[5.0149782e-07 4.2646451e-04 1.3355752e-03 3.9016623e-02 3.5850931e-05
  9.5918477e-01 2.5767019e-08 3.7722330e-08 3.7057628e-11 3.0847538e-09]]
[[0 0 0 0 0 1 0 0 0 0]]


/usr/local/lib/python3.7/dist-packages/librosa/core/audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn("PySoundFile failed. Trying audioread instead.")


kedi.m4a
tahmin [[4.9936077e-09 7.2012961e-05 6.5238931e-04 1.4279211e-02 7.9150265e-04
  9.8420483e-01 6.3444477e-10 1.7406870e-09 1.6794357e-13 5.4738655e-11]]
[[0 0 0 0 0 1 0 0 0 0]]


/usr/local/lib/python3.7/dist-packages/librosa/core/audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn("PySoundFile failed. Trying audioread instead.")


kopek (2).m4a
tahmin [[3.7707611e-08 1.0463890e-03 2.2816535e-03 1.0066134e-02 8.0643734e-04
  9.8579943e-01 1.3720942e-08 2.4214525e-08 8.6742176e-12 1.1864359e-09]]
[[0 0 0 0 0 1 0 0 0 0]]


/usr/local/lib/python3.7/dist-packages/librosa/core/audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn("PySoundFile failed. Trying audioread instead.")


kopek (1).m4a
tahmin [[4.4469534e-08 4.6808639e-04 1.2823696e-03 1.6644128e-02 2.4584893e-04
  9.8135948e-01 6.8741595e-09 1.1591149e-08 3.8760167e-12 5.8685728e-10]]
[[0 0 0 0 0 1 0 0 0 0]]


/usr/local/lib/python3.7/dist-packages/librosa/core/audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn("PySoundFile failed. Trying audioread instead.")


dogs.m4a
tahmin [[2.9484050e-07 1.0288316e-03 1.9855110e-03 2.2264469e-02 1.6676921e-04
  9.7455400e-01 3.9689297e-08 5.8653512e-08 5.1605612e-11 4.3992903e-09]]
[[0 0 0 0 0 1 0 0 0 0]]


/usr/local/lib/python3.7/dist-packages/librosa/core/audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn("PySoundFile failed. Trying audioread instead.")


kopekmic.m4a
tahmin [[3.9444380e-08 4.4314418e-04 8.8563486e-04 1.4376246e-02 2.3399107e-04
  9.8406082e-01 6.9654944e-09 1.1086059e-08 4.1213040e-12 5.8387428e-10]]
[[0 0 0 0 0 1 0 0 0 0]]


/usr/local/lib/python3.7/dist-packages/librosa/core/audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn("PySoundFile failed. Trying audioread instead.")


oksurt.m4a
tahmin [[5.7206012e-08 1.6907213e-04 7.1565009e-04 2.3764448e-02 4.9517294e-05
  9.7530127e-01 3.9751997e-09 7.0278583e-09 2.5569082e-12 3.6977657e-10]]
[[0 0 0 0 0 1 0 0 0 0]]


/usr/local/lib/python3.7/dist-packages/librosa/core/audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn("PySoundFile failed. Trying audioread instead.")


oksurme.m4a
tahmin [[2.2294126e-08 9.6404096e-05 4.1497441e-04 2.3734627e-02 4.0203613e-05
  9.7571373e-01 1.1706860e-09 2.0894508e-09 4.4361753e-13 9.3980587e-11]]
[[0 0 0 0 0 1 0 0 0 0]]


/usr/local/lib/python3.7/dist-packages/librosa/core/audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn("PySoundFile failed. Trying audioread instead.")


notrerdemm.m4a
tahmin [[4.6573626e-07 3.7651122e-04 1.2864691e-03 4.2935416e-02 2.9172616e-05
  9.5537192e-01 1.9156488e-08 2.8110264e-08 2.4336420e-11 2.2464042e-09]]
[[0 0 0 0 0 1 0 0 0 0]]


/usr/local/lib/python3.7/dist-packages/librosa/core/audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn("PySoundFile failed. Trying audioread instead.")


kizginerdem.m4a
tahmin [[4.3800367e-07 3.8133768e-04 1.3538329e-03 3.8723595e-02 2.7348133e-05
  9.5951337e-01 2.3519096e-08 3.5137589e-08 3.2826707e-11 2.7217593e-09]]
[[0 0 0 0 0 1 0 0 0 0]]


/usr/local/lib/python3.7/dist-packages/librosa/core/audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn("PySoundFile failed. Trying audioread instead.")


insann.m4a
tahmin [[1.7186416e-07 2.1681053e-04 7.5578783e-04 3.3044279e-02 1.7757000e-05
  9.6596521e-01 7.7215248e-09 1.1632287e-08 7.0762450e-12 7.7706303e-10]]
[[0 0 0 0 0 1 0 0 0 0]]


/usr/local/lib/python3.7/dist-packages/librosa/core/audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn("PySoundFile failed. Trying audioread instead.")


keddi.m4a
tahmin [[1.4694375e-08 1.1251751e-04 4.8000898e-04 2.0234251e-02 7.0232862e-05
  9.7910303e-01 9.8472264e-10 1.8387362e-09 3.1173602e-13 7.5312430e-11]]
[[0 0 0 0 0 1 0 0 0 0]]


/usr/local/lib/python3.7/dist-packages/librosa/core/audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn("PySoundFile failed. Trying audioread instead.")


keddddi.m4a
tahmin [[4.8838884e-09 4.4547440e-05 4.0027479e-04 1.3091610e-02 2.4058130e-04
  9.8622292e-01 5.3631227e-10 1.4262975e-09 1.6313017e-13 4.5555719e-11]]
[[0 0 0 0 0 1 0 0 0 0]]


/usr/local/lib/python3.7/dist-packages/librosa/core/audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn("PySoundFile failed. Trying audioread instead.")


erdem (1).m4a
tahmin [[8.3258578e-07 9.0474699e-04 1.7640936e-03 4.5185935e-02 2.9161254e-05
  9.5211518e-01 4.1013678e-08 4.8399073e-08 5.6672517e-11 4.4680428e-09]]
[[0 0 0 0 0 1 0 0 0 0]]


/usr/local/lib/python3.7/dist-packages/librosa/core/audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn("PySoundFile failed. Trying audioread instead.")


erdem.m4a
tahmin [[3.4125161e-08 1.0912342e-04 4.5272306e-04 2.5529116e-02 2.5659028e-05
  9.7388327e-01 1.7381577e-09 2.9678819e-09 8.0902673e-13 1.4298616e-10]]
[[0 0 0 0 0 1 0 0 0 0]]
keddddi.wav
tahmin [[4.8838884e-09 4.4547440e-05 4.0027479e-04 1.3091610e-02 2.4058130e-04
  9.8622292e-01 5.3631227e-10 1.4262975e-09 1.6313017e-13 4.5555719e-11]]
[[0 0 0 0 0 1 0 0 0 0]]


In [ ]:
dataFrame= dataFrame.replace(to_replace ="oksurme",value =3)
dataFrame= dataFrame.replace(to_replace ="ciglik",value =4)
dataFrame= dataFrame.replace(to_replace ="nefes",value =5)

dataFrame= dataFrame.replace(to_replace ="human",value =0)
dataFrame= dataFrame.replace(to_replace ="dogs",value =1)
dataFrame= dataFrame.replace(to_replace ="cats",value =2)

array([[0.        , 1.        , 0.6672305 , 0.7377542 , 0.78056455,
        0.7463647 , 0.72604406, 0.73894876, 0.7259226 , 0.73459166,
        0.7145661 , 0.72469467, 0.71541536, 0.72417164, 0.7194689 ,
        0.7271407 , 0.71078545, 0.73733556, 0.7223447 , 0.715758  ,
        0.6960286 , 0.71849096, 0.71950406, 0.7327919 , 0.71715635,
        0.7148852 , 0.7064781 , 0.72398806, 0.71195376, 0.71836406,
        0.71637625, 0.725074  , 0.71237683, 0.7249876 , 0.7084328 ,
        0.71712726, 0.7092081 , 0.7212776 , 0.7110273 , 0.72073424]],
      dtype=float32)